### ISSUE TITLE
Is it possible to write multiple groups with the same tag name?

### ISSUE THREAD

**Issue by fantapop** [sealsystems/node-ipp#8]
https://github.com/sealsystems/node-ipp/blob/640a46539c90571a943e266e171e0d3aea3934e0/lib/serializer.js#L314

Hi, I'm trying to implement the Get-Jobs call.  It appears that it returns multiple groups of the type job-attributes-tag.   You can see the definition here: https://tools.ietf.org/html/rfc2911#page-57
Since the format to pass into the serializer is an object keyed off of the group tag name it seems like multiple groups are not supported currently. Am i missing something here?

**Comment by StefanScherer** [comment]
Can you share more details what you are implementing?

I tried the ipp module as a client to receive a Get-Jobs response from CUPS. What I can see is this

```
{ version: '2.0',
  statusCode: 'successful-ok',
  id: 29863851,
  'operation-attributes-tag': 
   { 'attributes-charset': 'utf-8',
     'attributes-natural-language': 'en-us' },
  'job-attributes-tag': 
   [ { 'job-uri': 'ipp://localhost:6631/jobs/1',
       'job-originating-user-name': 'stefan',
       'job-name': 'whatever.pdf',
       'job-id': 1,
       'job-state': 'processing',
       'job-state-reasons': 'job-printing',
       'job-media-sheets-completed': 1 },
     { 'job-uri': 'ipp://localhost:6631/jobs/2',
       'job-originating-user-name': 'stefan',
       'job-name': 'whatever.pdf',
       'job-id': 2,
       'job-state': 'pending',
       'job-state-reasons': 'none',
       'job-media-sheets-completed': 0 },
     { 'job-uri': 'ipp://localhost:6631/jobs/3',
       'job-originating-user-name': 'stefan',
       'job-name': 'whatever.pdf',
       'job-id': 3,
       'job-state': 'pending',
       'job-state-reasons': 'none',
       'job-media-sheets-completed': 0 } ] }
```

I get one job-attributes-tag group with an array of jobs.

**Comment by StefanScherer** [comment]
Ok, this is what the parser returns. CUPS itself returns multiple job-attributes-tag objects.
